### ISSUE TITLE
Editable CSS editing in FF

### ISSUE THREAD

**Issue by estelle** [meyerweb/csstdg5figs#10]
The contenteditable CSS is no longer editable in FF. It still works in Chrome/Edge. You can write, but not remove text. something is up with the read-write ability.

**Comment by estelle** [comment]
https://meyerweb.github.io/csstdg4figs/18-animations/nameaddedlater.html - as an example

**Comment by estelle** [comment]
The issue seems to be that you can't delete text if the `<style>` is in the head. Works fine in FF in the body.

Should we trouble shoot why or move all the blocks out of the head?

**Comment by meyerweb** [comment]
If there’s a way to move them, I think it’s the way to go.

**Comment by estelle** [comment]
I'm not sure if you can view this link, but Onkar basically wrote a script for us, though we don't want to use prettier .... https://discord.com/channels/1009925603572600863/1050153889774710877/1079279890307751956

**Comment by estelle** [comment]
I was thinkingo of just removing all `</head><body>` from any `</style></head><body>` and replace all `<style id="editme"` with `</head><body><style id="editme"` . His solution is more elegant.

**Comment by meyerweb** [comment]
This is mostly, but probably not completely, dealt with.  I haven’t done a directory-wide search yet to make sure I caught all the instances.

**Comment by meyerweb** [comment]
Never mind!  I realized there was a fairly straightforward grep I could run — so I did, found one last page I had to fix, fixed it, and pushed it.
